### ISSUE TITLE
发送评论失败 提示strconv.ParseInt: parsing "BV1xx411c7mQ": invalid syntax

### ISSUE THREAD

**Issue by liuqianpan2008** [Ninzore/bilibili-captain#1]
发送评论时提示`strconv.ParseInt: parsing "BV1xx411c7mQ": invalid syntax`
具体代码
<img width="797" alt="image" src="https://user-images.githubusercontent.com/80571808/185879421-57d77ea2-4654-4a6c-922d-ae583e6bda37.png">
控制台的输出
<img width="1383" alt="image" src="https://user-images.githubusercontent.com/80571808/185879542-3d1442d5-3a5b-426a-bc51-da9c00b0fa61.png">
不知道是我写错了，求佬帮忙看看

**Comment by Ninzore** [comment]
好我看看，虽然我自己都忘了怎么写的了

**Comment by Ninzore** [comment]
我修了一下，然后发现你这里是因为把BV俩字给传进去导致报错的。我修错地方了

**Comment by Ninzore** [comment]
`BV1xx411c7mQ`这个是`AV1`吧，这视频早就没了所以评论出错？我测试别的视频是好的。
